name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lisnxAHQL7WUTvFe"
GITHUB_OWNER = "lu87sy"
GITHUB_REPO = "NavSite"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://lu87sy.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://lu87sy.dpdns.org"

